# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Val < Formula
  desc "Val — security & risk intelligence from your terminal"
  homepage "https://valoryck.com"
  version "0.1.1"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/valoryck/val/releases/download/v0.1.1/val_0.1.1_darwin_amd64.tar.gz"
      sha256 "f3f26249dc41b0cf30912bf4d9b0db8601487c980ad355c73df1e92b7053f5a5"

      define_method(:install) do
        bin.install "val"
        generate_completions_from_executable(bin/"val", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/valoryck/val/releases/download/v0.1.1/val_0.1.1_darwin_arm64.tar.gz"
      sha256 "51130003be37523b8d6a465a28a63907ecea155a0b0d8e58de1a34cbbc72deb6"

      define_method(:install) do
        bin.install "val"
        generate_completions_from_executable(bin/"val", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/valoryck/val/releases/download/v0.1.1/val_0.1.1_linux_amd64.tar.gz"
      sha256 "edf910303f474536948375bc3b18931ceab74b9e35a2c8816a64f04733c2e8c3"
      define_method(:install) do
        bin.install "val"
        generate_completions_from_executable(bin/"val", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/valoryck/val/releases/download/v0.1.1/val_0.1.1_linux_arm64.tar.gz"
      sha256 "7ade5b81512aa4ddaf22ecca901c5086a11d8b795cf81f74cf08460a6cfeb87e"
      define_method(:install) do
        bin.install "val"
        generate_completions_from_executable(bin/"val", "completion")
      end
    end
  end

  test do
    assert_match "val", shell_output("#{bin}/val version")
  end
end
