# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Val < Formula
  desc "Val — security & risk intelligence from your terminal"
  homepage "https://valoryck.com"
  version "0.1.0"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/valoryck/val/releases/download/v0.1.0/val_0.1.0_darwin_amd64.tar.gz"
      sha256 "38b7f69eddaba208fa9952b0f2ee358b12fc5ab5a8d94f3bad84a92427701431"

      define_method(:install) do
        bin.install "val"
        generate_completions_from_executable(bin/"val", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/valoryck/val/releases/download/v0.1.0/val_0.1.0_darwin_arm64.tar.gz"
      sha256 "819d41c008527b3a6484ab6104f3da233a1988f74b5db8c92d5268d9d9860109"

      define_method(:install) do
        bin.install "val"
        generate_completions_from_executable(bin/"val", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/valoryck/val/releases/download/v0.1.0/val_0.1.0_linux_amd64.tar.gz"
      sha256 "2593204ec5f84b07c1dd6c1fa755627460b2ed3d702b362cb5e44e64b92a56dc"
      define_method(:install) do
        bin.install "val"
        generate_completions_from_executable(bin/"val", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/valoryck/val/releases/download/v0.1.0/val_0.1.0_linux_arm64.tar.gz"
      sha256 "63fbc47197d7662681c4932579ac283925b0e5078fdd6364f3c846612245fbb5"
      define_method(:install) do
        bin.install "val"
        generate_completions_from_executable(bin/"val", "completion")
      end
    end
  end

  test do
    assert_match "val", shell_output("#{bin}/val version")
  end
end
